# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  mail:
    host: smtp.163.com
    username: YiXiMi2025@163.com
    password: BU2CkRhHMRUv6uwG
    port: 465
    properties:
      from: YiXiMi2025@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/monitor
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: abcdefghijk
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'